version: "3.2"

services:
  ukr-dashboard-db:
    image: mysql:8.0
    container_name: ukr-dashboard-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ukrdashboard
    ports:
      - "8011:3306"
    networks:
      - podkor

networks:
  podkor:
    external: false
